# Configurações do Clippy

# Limites específicos de configuração
too-many-arguments-threshold = 7
cognitive-complexity-threshold = 25
# Regras automáticas baseadas em padrões de erro
# Gerado automaticamente pelo sistema de prevenção

