[server]
bindAddress = "0.0.0.0:8787"
tlsEnabled = false
tlsCertPath = "/app/certs/mcp-server.crt" # Corrigido de cert_path para tlsCertPath
tlsKeyPath = "/app/certs/mcp-server.key"  # Corrigido de key_path para tlsKeyPath

[typedb]
address = "typedb-server-it:1729"
username = "admin"
tlsEnabled = false

[auth]
enabled = false # Corrigido de oauth_enabled para enabled
jwksUri = ""    # Corrigido de oauth_jwks_uri para jwksUri
