version: '3.8'

services:
  typedb-mcp-server-it:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787" # Porta HTTP/WebSocket padrão do MCP Server
      - "8443:8443" # Porta HTTPS/WSS opcional (caso TLS seja ativado nos testes)
    depends_on:
      - typedb-server-it
      - mock-oauth2-server # Adicionada dependência
    networks:
      - typedb_mcp_test_network
    environment: # Adicionado para garantir a conexão correta com o TypeDB
      - MCP_CONFIG_PATH=/app/config.test.toml # Adicionado para garantir o uso do config de teste
      - MCP_TYPEDB__ADDRESS=typedb-server-it:1729
      - RUST_LOG=info,typedb_mcp_server_lib=trace,typedb_driver=trace,hyper=trace # Adicionado hyper=trace
    restart: "no"
    healthcheck: # Ajustado para maior robustez em ambientes de CI/CD
      test: ["CMD-SHELL", "curl -f -v http://localhost:8787/livez 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

  typedb-server-it:
    image: typedb/typedb:3.2.0
    environment:
      - TYPEDB_SERVER_OPTS=--server.authentication.enable=false
    healthcheck: # Corrigido para não depender de nc (netcat)
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/1729' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10 # Mais retries para TypeDB
      start_period: 45s # Período de inicialização maior para TypeDB
    networks:
      - typedb_mcp_test_network

  mock-oauth2-server:
    image: nginx:1.25-alpine
    ports:
      - "8088" # Porta dinâmica será atribuída pelo Docker
    volumes:
      - ./mock_jwks.json:/usr/share/nginx/html/.well-known/jwks.json:ro
      - ./scripts/nginx-mock-oauth2.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - typedb_mcp_test_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/livez || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  typedb_mcp_test_network:
    driver: bridge

volumes:
  typedb_data_it:
  typedb_logs_it: