version: '3.8'

services:
  typedb-mcp-server-it:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: typedb-mcp-server-it-compose
    ports:
      - "${MCP_SERVER_TEST_PORT:-8788}:8787"
    volumes:
      - ./config.test.toml:/app/typedb_mcp_server_config.toml:ro
      - ./certs/generated-dev:/app/certs:ro # Atualizado para generated-dev
    environment:
      - RUST_LOG=${RUST_LOG:-info,typedb_mcp_server_lib=debug}
      - MCP_CONFIG_PATH=/app/typedb_mcp_server_config.toml
      - TYPEDB_ADDRESS=typedb-server-it:1729
      - TYPEDB_USERNAME=${TYPEDB_USERNAME:-admin}
      - TYPEDB_PASSWORD=${TYPEDB_PASSWORD}
      - TYPEDB_TLS_ENABLED=${TYPEDB_TLS_ENABLED:-false}
      - TYPEDB_TLS_CA_PATH=${TYPEDB_TLS_CA_PATH:-/app/certs/ca.pem} # Atualizado para ca.pem
      - MCP_SERVER_TLS_ENABLED=${MCP_SERVER_TLS_ENABLED:-false}
      - MCP_SERVER_CERT_PATH=${MCP_SERVER_CERT_PATH:-/app/certs/mcp-server.pem} # Atualizado para mcp-server.pem
      - MCP_SERVER_KEY_PATH=${MCP_SERVER_KEY_PATH:-/app/certs/mcp-server-key.pem} # Atualizado para mcp-server-key.pem
      - MCP_AUTH_OAUTH_ENABLED=${MCP_AUTH_OAUTH_ENABLED:-false}
      - MCP_AUTH_OAUTH_JWKS_URI=${MCP_AUTH_OAUTH_JWKS_URI:-http://mock-oauth2-server:80/.well-known/jwks.json} # Adicionado valor padrão
    depends_on:
      - typedb-server-it
      - mock-oauth2-server # Adicionada dependência
    networks:
      - typedb_mcp_test_network
    restart: "no"

  typedb-server-it:
    image: typedb/typedb:3.2.0
    container_name: typedb-server-it-compose
    environment:
      - TYPEDB_SERVER_OPTS=--server.authentication.enable=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1729/health" ] # Corrigido para porta 1729
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - typedb_mcp_test_network

  mock-oauth2-server: # Novo serviço
    image: nginx:alpine
    container_name: mock-oauth2-server-compose
    ports:
      - "${MOCK_OAUTH_PORT:-8088}:80" # Permite configurar a porta do host
    volumes:
      - ./mock_jwks.json:/usr/share/nginx/html/.well-known/jwks.json:ro
      - ./scripts/nginx-mock-oauth2.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - typedb_mcp_test_network
    restart: "no"

networks:
  typedb_mcp_test_network:
    driver: bridge
