version: '3.8'

services:
  typedb-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: typedb-mcp-server
    ports:
      - "${MCP_SERVER_PORT_HTTP:-8787}:8787"
      - "${MCP_SERVER_PORT_HTTPS:-8443}:8443"
      - "${MCP_METRICS_PORT:-9090}:9090"
    volumes:
      - ./config.dev.toml:/app/typedb_mcp_server_config.toml:ro
      - ./certs/generated:/app/certs:ro
    environment:
      - RUST_LOG=${RUST_LOG:-info,typedb_mcp_server_lib=debug}
      - MCP_CONFIG_PATH=/app/typedb_mcp_server_config.toml
      - TYPEDB_ADDRESS=typedb-server-dev:1729
      - TYPEDB_USERNAME=${TYPEDB_USERNAME:-admin}
      - TYPEDB_PASSWORD_FILE=/run/secrets/db_password
      - TYPEDB_TLS_ENABLED=${TYPEDB_TLS_ENABLED:-false}
      - TYPEDB_TLS_CA_PATH=${TYPEDB_TLS_CA_PATH:-/app/certs/typedb-ca.pem}
      - MCP_SERVER_TLS_ENABLED=${MCP_SERVER_TLS_ENABLED:-false}
      - MCP_SERVER_CERT_PATH=${MCP_SERVER_CERT_PATH:-/app/certs/mcp-server.crt}
      - MCP_SERVER_KEY_PATH=${MCP_SERVER_KEY_PATH:-/app/certs/mcp-server.key}
      - MCP_AUTH_OAUTH_ENABLED=${MCP_AUTH_OAUTH_ENABLED:-false}
      - MCP_AUTH_OAUTH_JWKS_URI=${MCP_AUTH_OAUTH_JWKS_URI}
    depends_on:
      - typedb-server-dev
    networks:
      - typedb_mcp_network
    restart: unless-stopped
    secrets:
      - db_password

  typedb-server-dev:
    image: typedb/typedb:3.2.0
    container_name: typedb-server-dev-compose
    ports:
      - "${TYPEDB_DEV_GRPC_PORT:-1729}:1729"
      - "${TYPEDB_DEV_HTTP_PORT:-10080}:80"
    volumes:
      - typedb-dev-data:/opt/typedb/data
    environment:
      - TYPEDB_SERVER_OPTS=--server.authentication.enable=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80livez" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - typedb_mcp_network
    restart: unless-stopped

networks:
  typedb_mcp_network:
    driver: bridge

volumes:
  typedb-dev-data:

secrets:
  db_password:
    file: ./local-dev-secrets/password.txt
